version: '3'
services:
  # Spring Boot application
  backend:
    container_name: backend-app
    image: todolistwithapi-backend-image
    restart: always
    build: ./backend/todolistwithapi
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  # MySQL database
  mysql:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todolistwithapi
      MYSQL_ROOT_PASSWORD: root

  # Angular application
  frontend:
    container_name: frontend-app
    image: todolistwithapi-frontend-image
    build:
      context: ./frontend/todolistwithapi
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - backend
